export const FETCHING_REPO = "FETCHING_REPO";
export const FETCHING_REPO_SUCCESS = "FETCHING_REPO_SUCCESS";
export const FETCHING_REPO_FAILED = "FETCHING_REPO_FAILED";
export const DELETE_REPO = "DELETE_REPO";
export const TOGGLE_REPO = "TOGGLE_REPO";
